# File and Data Configuration
files:
  output_dir: "data"
  recorded_scan_path: "data/recorded_scan_path.npy"
  input_list:
    - "data/B-field_zoff_0.npy"
    - "data/B-field_zoff_5.npy"
    - "data/B-field_zoff_10.npy"
    - "data/B-field_zoff_15.npy"
    - "data/B-field_zoff_20.npy"
    - "data/B-field_zoff_25.npy"
    - "data/B-field_zoff_30.npy"
    - "data/B-field_zoff_35.npy"
  output_muxed_result: "binary_data.bin"

# System & Sensor Parameters
system_parameters:
  sensor_count: 8
  sensor_offsets: [0.0, .005, .010, .015, .020, .025, .030, .035]
  encoder_resolution: 1
  origin_m: [0, 0, 0]

# Sampling Configuration
sampling:
  rate_hz: 10000
  min_rate_hz: 10000
  max_rate_hz: 200000
  clock_start: 0
  dynamic_range_bits: 16

# Scan Motion Physics
motion_profile:
  acceleration_m_per_s2:
    x: 0.001
    y: 0.010
    z: 0.003
  max_velocity_m_per_s:
    x: 0.002
    y: 0.020
    z: 0.003

# Scan Sequence & Dimensions
scan_setup:
  dimensions_m:
    max_x: 0.300
    max_y: 0.300
    max_z: 0.300
  step_sizes_m:
    x: 0.010
    z: 0.030
  repetitions:
    x_axis: 30
    z_steps_per_plane: 10
  scan_counts: # Number of scans in each direction
    x: 0
    y: 3
    z: 3
  durations_s:
    y_scan: 17.0
    z_scan: 11.0
    x_scan: 7.0

# Simulation-specific Objects
simulation_objects:
  system_under_test:
    type: "Sphere"
    diameter: 0.150
    polarization: [500, 0, 500]
    position_m: {x: 0.150, y: 0.150, z: 0.150}

  scan_vectors:
    pos_y_sweep: [0, 0.300, 0]
    pos_z_shift: [0, 0, 0.015]
    x_shift: [0.010, 0, 0]

# Initial State Variables for Simulation Runtime
initial_runtime_state:
  current_position: {x: 0.0, y: 0.0, z: 0.0}
  path_segments: []
